/*
=============================================================================
SCHEMA: All
DATABASE: bharat_railway_core
MODULE: Seed Data - Real Indian Railway Data
AUTHOR: Chandra Shekhar Bansal (Network/DB Engineer)
VERSION: 1.0.0
ENGINE: PostgreSQL 15+
=============================================================================
*/

-- =============================================
-- STATIONS (50 Major Stations with Geo Coordinates)
-- =============================================
INSERT INTO
    train_master_schema.stations (
        station_code,
        station_name,
        city,
        state,
        zone,
        division,
        station_category,
        station_type,
        number_of_platforms,
        pincode,
        station_status,
        opening_year
    )
VALUES (
        'NDLS',
        'New Delhi',
        'Delhi',
        'Delhi',
        'Northern Railway',
        'Delhi Division',
        'A1',
        'Central',
        16,
        '110001',
        'Active',
        1926
    ),
    (
        'DLI',
        'Old Delhi',
        'Delhi',
        'Delhi',
        'Northern Railway',
        'Delhi Division',
        'A1',
        'Junction',
        16,
        '110006',
        'Active',
        1864
    ),
    (
        'NZM',
        'Hazrat Nizamuddin',
        'Delhi',
        'Delhi',
        'Northern Railway',
        'Delhi Division',
        'A1',
        'Terminal',
        7,
        '110013',
        'Active',
        1976
    ),
    (
        'ANVT',
        'Anand Vihar Terminal',
        'Delhi',
        'Delhi',
        'Northern Railway',
        'Delhi Division',
        'A1',
        'Terminal',
        7,
        '110092',
        'Active',
        2009
    ),
    (
        'BCT',
        'Mumbai Central',
        'Mumbai',
        'Maharashtra',
        'Western Railway',
        'Mumbai Division',
        'A1',
        'Terminal',
        9,
        '400008',
        'Active',
        1930
    ),
    (
        'CSTM',
        'CSMT Mumbai',
        'Mumbai',
        'Maharashtra',
        'Central Railway',
        'Mumbai Division',
        'A1',
        'Terminal',
        18,
        '400001',
        'Active',
        1888
    ),
    (
        'LTT',
        'Lokmanya Tilak Terminus',
        'Mumbai',
        'Maharashtra',
        'Central Railway',
        'Mumbai Division',
        'A1',
        'Terminal',
        5,
        '400089',
        'Active',
        1991
    ),
    (
        'DDR',
        'Dadar',
        'Mumbai',
        'Maharashtra',
        'Western Railway',
        'Mumbai Division',
        'A1',
        'Junction',
        15,
        '400014',
        'Active',
        1868
    ),
    (
        'HWH',
        'Howrah',
        'Kolkata',
        'West Bengal',
        'Eastern Railway',
        'Howrah Division',
        'A1',
        'Terminal',
        23,
        '711101',
        'Active',
        1854
    ),
    (
        'SDAH',
        'Sealdah',
        'Kolkata',
        'West Bengal',
        'Eastern Railway',
        'Sealdah Division',
        'A1',
        'Terminal',
        21,
        '700014',
        'Active',
        1869
    ),
    (
        'KOAA',
        'Kolkata',
        'Kolkata',
        'West Bengal',
        'Eastern Railway',
        'Sealdah Division',
        'A1',
        'Terminal',
        5,
        '700037',
        'Active',
        2006
    ),
    (
        'MAS',
        'Chennai Central',
        'Chennai',
        'Tamil Nadu',
        'Southern Railway',
        'Chennai Division',
        'A1',
        'Terminal',
        12,
        '600003',
        'Active',
        1873
    ),
    (
        'MS',
        'Chennai Egmore',
        'Chennai',
        'Tamil Nadu',
        'Southern Railway',
        'Chennai Division',
        'A1',
        'Terminal',
        11,
        '600008',
        'Active',
        1908
    ),
    (
        'SBC',
        'KSR Bengaluru',
        'Bengaluru',
        'Karnataka',
        'South Western Railway',
        'Bengaluru Division',
        'A1',
        'Terminal',
        10,
        '560023',
        'Active',
        1968
    ),
    (
        'YPR',
        'Yesvantpur',
        'Bengaluru',
        'Karnataka',
        'South Western Railway',
        'Bengaluru Division',
        'A1',
        'Terminal',
        6,
        '560022',
        'Active',
        1980
    ),
    (
        'SC',
        'Secunderabad',
        'Hyderabad',
        'Telangana',
        'South Central Railway',
        'Secunderabad Division',
        'A1',
        'Junction',
        10,
        '500003',
        'Active',
        1874
    ),
    (
        'HYB',
        'Hyderabad Deccan',
        'Hyderabad',
        'Telangana',
        'South Central Railway',
        'Hyderabad Division',
        'A1',
        'Terminal',
        6,
        '500001',
        'Active',
        1907
    ),
    (
        'ADI',
        'Ahmedabad',
        'Ahmedabad',
        'Gujarat',
        'Western Railway',
        'Ahmedabad Division',
        'A1',
        'Junction',
        12,
        '380002',
        'Active',
        1864
    ),
    (
        'BRC',
        'Vadodara',
        'Vadodara',
        'Gujarat',
        'Western Railway',
        'Vadodara Division',
        'A1',
        'Junction',
        7,
        '390005',
        'Active',
        1861
    ),
    (
        'ST',
        'Surat',
        'Surat',
        'Gujarat',
        'Western Railway',
        'Mumbai Division',
        'A1',
        'Junction',
        4,
        '395003',
        'Active',
        1864
    ),
    (
        'JP',
        'Jaipur',
        'Jaipur',
        'Rajasthan',
        'North Western Railway',
        'Jaipur Division',
        'A1',
        'Junction',
        7,
        '302006',
        'Active',
        1875
    ),
    (
        'AII',
        'Ajmer',
        'Ajmer',
        'Rajasthan',
        'North Western Railway',
        'Ajmer Division',
        'A1',
        'Junction',
        5,
        '305001',
        'Active',
        1876
    ),
    (
        'JU',
        'Jodhpur',
        'Jodhpur',
        'Rajasthan',
        'North Western Railway',
        'Jodhpur Division',
        'A1',
        'Junction',
        5,
        '342001',
        'Active',
        1885
    ),
    (
        'LKO',
        'Lucknow',
        'Lucknow',
        'Uttar Pradesh',
        'Northern Railway',
        'Lucknow Division',
        'A1',
        'Junction',
        9,
        '226001',
        'Active',
        1867
    ),
    (
        'CNB',
        'Kanpur Central',
        'Kanpur',
        'Uttar Pradesh',
        'North Central Railway',
        'Allahabad Division',
        'A1',
        'Central',
        10,
        '208001',
        'Active',
        1859
    ),
    (
        'ALD',
        'Prayagraj',
        'Prayagraj',
        'Uttar Pradesh',
        'North Central Railway',
        'Allahabad Division',
        'A1',
        'Junction',
        10,
        '211003',
        'Active',
        1867
    ),
    (
        'BSB',
        'Varanasi',
        'Varanasi',
        'Uttar Pradesh',
        'Northern Railway',
        'Lucknow Division',
        'A1',
        'Junction',
        9,
        '221002',
        'Active',
        1862
    ),
    (
        'AGC',
        'Agra Cantt',
        'Agra',
        'Uttar Pradesh',
        'North Central Railway',
        'Agra Division',
        'A1',
        'Cantonment',
        6,
        '282001',
        'Active',
        1904
    ),
    (
        'GWL',
        'Gwalior',
        'Gwalior',
        'Madhya Pradesh',
        'North Central Railway',
        'Jhansi Division',
        'A1',
        'Junction',
        5,
        '474002',
        'Active',
        1881
    ),
    (
        'BPL',
        'Bhopal',
        'Bhopal',
        'Madhya Pradesh',
        'West Central Railway',
        'Bhopal Division',
        'A1',
        'Junction',
        6,
        '462001',
        'Active',
        1884
    ),
    (
        'JBP',
        'Jabalpur',
        'Jabalpur',
        'Madhya Pradesh',
        'West Central Railway',
        'Jabalpur Division',
        'A1',
        'Junction',
        6,
        '482001',
        'Active',
        1867
    ),
    (
        'NGP',
        'Nagpur',
        'Nagpur',
        'Maharashtra',
        'Central Railway',
        'Nagpur Division',
        'A1',
        'Junction',
        8,
        '440001',
        'Active',
        1867
    ),
    (
        'PUNE',
        'Pune',
        'Pune',
        'Maharashtra',
        'Central Railway',
        'Pune Division',
        'A1',
        'Junction',
        6,
        '411001',
        'Active',
        1858
    ),
    (
        'SUR',
        'Solapur',
        'Solapur',
        'Maharashtra',
        'Central Railway',
        'Solapur Division',
        'A1',
        'Junction',
        5,
        '413001',
        'Active',
        1862
    ),
    (
        'BBS',
        'Bhubaneswar',
        'Bhubaneswar',
        'Odisha',
        'East Coast Railway',
        'Khurda Road Division',
        'A1',
        'Junction',
        6,
        '751001',
        'Active',
        1896
    ),
    (
        'PURI',
        'Puri',
        'Puri',
        'Odisha',
        'East Coast Railway',
        'Khurda Road Division',
        'A1',
        'Terminal',
        5,
        '752001',
        'Active',
        1897
    ),
    (
        'VSKP',
        'Visakhapatnam',
        'Visakhapatnam',
        'Andhra Pradesh',
        'East Coast Railway',
        'Waltair Division',
        'A1',
        'Junction',
        8,
        '530001',
        'Active',
        1894
    ),
    (
        'BZA',
        'Vijayawada',
        'Vijayawada',
        'Andhra Pradesh',
        'South Central Railway',
        'Vijayawada Division',
        'A1',
        'Junction',
        10,
        '520001',
        'Active',
        1888
    ),
    (
        'GNT',
        'Guntur',
        'Guntur',
        'Andhra Pradesh',
        'South Central Railway',
        'Guntur Division',
        'A',
        'Junction',
        5,
        '522001',
        'Active',
        1890
    ),
    (
        'TPTY',
        'Tirupati',
        'Tirupati',
        'Andhra Pradesh',
        'South Central Railway',
        'Guntakal Division',
        'A1',
        'Terminal',
        5,
        '517501',
        'Active',
        1893
    ),
    (
        'CBE',
        'Coimbatore',
        'Coimbatore',
        'Tamil Nadu',
        'Southern Railway',
        'Salem Division',
        'A1',
        'Junction',
        6,
        '641001',
        'Active',
        1862
    ),
    (
        'ED',
        'Erode',
        'Erode',
        'Tamil Nadu',
        'Southern Railway',
        'Salem Division',
        'A',
        'Junction',
        5,
        '638001',
        'Active',
        1862
    ),
    (
        'MDU',
        'Madurai',
        'Madurai',
        'Tamil Nadu',
        'Southern Railway',
        'Madurai Division',
        'A1',
        'Junction',
        5,
        '625001',
        'Active',
        1875
    ),
    (
        'TVC',
        'Thiruvananthapuram',
        'Thiruvananthapuram',
        'Kerala',
        'Southern Railway',
        'Thiruvananthapuram Division',
        'A1',
        'Central',
        5,
        '695001',
        'Active',
        1902
    ),
    (
        'ERS',
        'Ernakulam',
        'Kochi',
        'Kerala',
        'Southern Railway',
        'Thiruvananthapuram Division',
        'A1',
        'Junction',
        6,
        '682016',
        'Active',
        1902
    ),
    (
        'CLT',
        'Kozhikode',
        'Kozhikode',
        'Kerala',
        'Southern Railway',
        'Palakkad Division',
        'A',
        'Junction',
        4,
        '673001',
        'Active',
        1888
    ),
    (
        'MAQ',
        'Mangaluru',
        'Mangaluru',
        'Karnataka',
        'Southern Railway',
        'Palakkad Division',
        'A1',
        'Central',
        4,
        '575001',
        'Active',
        1907
    ),
    (
        'UBL',
        'Hubballi',
        'Hubballi',
        'Karnataka',
        'South Western Railway',
        'Hubballi Division',
        'A',
        'Junction',
        5,
        '580020',
        'Active',
        1886
    ),
    (
        'GTL',
        'Guntakal',
        'Guntakal',
        'Andhra Pradesh',
        'South Central Railway',
        'Guntakal Division',
        'A',
        'Junction',
        5,
        '515801',
        'Active',
        1871
    ),
    (
        'RNC',
        'Ranchi',
        'Ranchi',
        'Jharkhand',
        'South Eastern Railway',
        'Ranchi Division',
        'A1',
        'Junction',
        5,
        '834001',
        'Active',
        1908
    ),
    (
        'PNBE',
        'Patna',
        'Patna',
        'Bihar',
        'East Central Railway',
        'Danapur Division',
        'A1',
        'Junction',
        10,
        '800001',
        'Active',
        1862
    ),
    (
        'GAYA',
        'Gaya',
        'Gaya',
        'Bihar',
        'East Central Railway',
        'Mughalsarai Division',
        'A',
        'Junction',
        5,
        '823001',
        'Active',
        1879
    ),
    (
        'DHN',
        'Dhanbad',
        'Dhanbad',
        'Jharkhand',
        'East Central Railway',
        'Dhanbad Division',
        'A1',
        'Junction',
        8,
        '826001',
        'Active',
        1894
    ),
    (
        'BQA',
        'Bankura',
        'Bankura',
        'West Bengal',
        'South Eastern Railway',
        'Adra Division',
        'B',
        'Junction',
        3,
        '722101',
        'Active',
        1901
    ),
    (
        'GKP',
        'Gorakhpur',
        'Gorakhpur',
        'Uttar Pradesh',
        'North Eastern Railway',
        'Lucknow Division',
        'A1',
        'Junction',
        8,
        '273001',
        'Active',
        1885
    ),
    (
        'ASR',
        'Amritsar',
        'Amritsar',
        'Punjab',
        'Northern Railway',
        'Firozpur Division',
        'A1',
        'Junction',
        6,
        '143001',
        'Active',
        1862
    ),
    (
        'CDG',
        'Chandigarh',
        'Chandigarh',
        'Chandigarh',
        'Northern Railway',
        'Ambala Division',
        'A1',
        'Junction',
        5,
        '160101',
        'Active',
        1954
    ),
    (
        'UMB',
        'Ambala Cantt',
        'Ambala',
        'Haryana',
        'Northern Railway',
        'Ambala Division',
        'A1',
        'Cantonment',
        7,
        '133001',
        'Active',
        1869
    ),
    (
        'JAT',
        'Jammu Tawi',
        'Jammu',
        'Jammu & Kashmir',
        'Northern Railway',
        'Firozpur Division',
        'A1',
        'Junction',
        4,
        '180001',
        'Active',
        1975
    ),
    (
        'SVDK',
        'Shri Mata Vaishno Devi Katra',
        'Katra',
        'Jammu & Kashmir',
        'Northern Railway',
        'Firozpur Division',
        'A',
        'Terminal',
        3,
        '182301',
        'Active',
        2014
    ),
    (
        'GHC',
        'Ghaziabad',
        'Ghaziabad',
        'Uttar Pradesh',
        'Northern Railway',
        'Delhi Division',
        'A1',
        'Junction',
        6,
        '201001',
        'Active',
        1866
    ),
    (
        'MB',
        'Moradabad',
        'Moradabad',
        'Uttar Pradesh',
        'Northern Railway',
        'Moradabad Division',
        'A',
        'Junction',
        6,
        '244001',
        'Active',
        1884
    ),
    (
        'RK',
        'Roorkee',
        'Roorkee',
        'Uttarakhand',
        'Northern Railway',
        'Moradabad Division',
        'A',
        'Junction',
        4,
        '247667',
        'Active',
        1868
    ),
    (
        'HW',
        'Haridwar',
        'Haridwar',
        'Uttarakhand',
        'Northern Railway',
        'Moradabad Division',
        'A',
        'Junction',
        5,
        '249401',
        'Active',
        1886
    ),
    (
        'DDN',
        'Dehradun',
        'Dehradun',
        'Uttarakhand',
        'Northern Railway',
        'Moradabad Division',
        'A',
        'Terminal',
        5,
        '248001',
        'Active',
        1900
    ),
    (
        'BE',
        'Bareilly',
        'Bareilly',
        'Uttar Pradesh',
        'Northern Railway',
        'Moradabad Division',
        'A',
        'Junction',
        5,
        '243001',
        'Active',
        1872
    ),
    (
        'LJN',
        'Lucknow Junction',
        'Lucknow',
        'Uttar Pradesh',
        'Northern Railway',
        'Lucknow Division',
        'A',
        'Junction',
        5,
        '226001',
        'Active',
        1867
    ),
    (
        'UDZ',
        'Udaipur',
        'Udaipur',
        'Rajasthan',
        'North Western Railway',
        'Ajmer Division',
        'A',
        'Terminal',
        3,
        '313001',
        'Active',
        1896
    ),
    (
        'BKN',
        'Bikaner',
        'Bikaner',
        'Rajasthan',
        'North Western Railway',
        'Bikaner Division',
        'A',
        'Junction',
        5,
        '334001',
        'Active',
        1891
    ),
    (
        'MTJ',
        'Mathura',
        'Mathura',
        'Uttar Pradesh',
        'North Central Railway',
        'Agra Division',
        'A',
        'Junction',
        8,
        '281001',
        'Active',
        1872
    ) ON CONFLICT (station_code) DO NOTHING;

-- =============================================
-- TRAINS (50 Major Trains)
-- =============================================
INSERT INTO
    train_master_schema.trains (
        train_number,
        train_name,
        train_type,
        category,
        origin_station_code,
        destination_station_code,
        total_distance,
        average_speed,
        maximum_speed,
        total_coaches,
        pantry_car,
        wifi_available,
        train_status,
        introduction_date,
        is_special_train,
        fare_multiplier,
        tatkal_available
    )
VALUES (
        '12951',
        'Mumbai Rajdhani',
        'Rajdhani',
        'Superfast',
        'BCT',
        'NDLS',
        1386,
        90,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1972-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12952',
        'Delhi Rajdhani',
        'Rajdhani',
        'Superfast',
        'NDLS',
        'BCT',
        1386,
        90,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1972-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12301',
        'Howrah Rajdhani',
        'Rajdhani',
        'Superfast',
        'HWH',
        'NDLS',
        1447,
        88,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1969-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12302',
        'Delhi Howrah Rajdhani',
        'Rajdhani',
        'Superfast',
        'NDLS',
        'HWH',
        1447,
        88,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1969-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12423',
        'Dibrugarh Rajdhani',
        'Rajdhani',
        'Superfast',
        'NDLS',
        'DBRG',
        2435,
        75,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1996-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12001',
        'Bhopal Shatabdi',
        'Shatabdi',
        'Superfast',
        'NDLS',
        'BPL',
        707,
        85,
        130,
        20,
        TRUE,
        TRUE,
        'Active',
        '1988-01-01',
        FALSE,
        1.15,
        TRUE
    ),
    (
        '12002',
        'Delhi Shatabdi',
        'Shatabdi',
        'Superfast',
        'BPL',
        'NDLS',
        707,
        85,
        130,
        20,
        TRUE,
        TRUE,
        'Active',
        '1988-01-01',
        FALSE,
        1.15,
        TRUE
    ),
    (
        '12009',
        'Mumbai Shatabdi',
        'Shatabdi',
        'Superfast',
        'ADI',
        'BCT',
        493,
        78,
        120,
        18,
        TRUE,
        TRUE,
        'Active',
        '1994-01-01',
        FALSE,
        1.15,
        TRUE
    ),
    (
        '12259',
        'Sealdah Duronto',
        'Duronto',
        'Superfast',
        'SDAH',
        'NDLS',
        1453,
        95,
        130,
        20,
        TRUE,
        TRUE,
        'Active',
        '2009-01-01',
        FALSE,
        1.10,
        TRUE
    ),
    (
        '12260',
        'Delhi Duronto',
        'Duronto',
        'Superfast',
        'NDLS',
        'SDAH',
        1453,
        95,
        130,
        20,
        TRUE,
        TRUE,
        'Active',
        '2009-01-01',
        FALSE,
        1.10,
        TRUE
    ),
    (
        '12909',
        'Bandra Garib Rath',
        'Garib Rath',
        'Superfast',
        'NZM',
        'BDTS',
        1367,
        70,
        110,
        18,
        FALSE,
        FALSE,
        'Active',
        '2006-01-01',
        FALSE,
        0.85,
        TRUE
    ),
    (
        '12430',
        'Bangalore Rajdhani',
        'Rajdhani',
        'Superfast',
        'SBC',
        'NZM',
        2365,
        80,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1992-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12621',
        'Tamil Nadu Express',
        'Superfast',
        'Superfast',
        'MAS',
        'NDLS',
        2182,
        75,
        110,
        22,
        TRUE,
        TRUE,
        'Active',
        '1964-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12622',
        'Delhi Tamil Nadu Exp',
        'Superfast',
        'Superfast',
        'NDLS',
        'MAS',
        2182,
        75,
        110,
        22,
        TRUE,
        TRUE,
        'Active',
        '1964-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12839',
        'Howrah Chennai Mail',
        'Mail',
        'Mail',
        'HWH',
        'MAS',
        1662,
        55,
        100,
        20,
        TRUE,
        FALSE,
        'Active',
        '1900-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '11015',
        'Kushinagar Express',
        'Express',
        'Express',
        'LTT',
        'GKP',
        1680,
        55,
        100,
        20,
        FALSE,
        FALSE,
        'Active',
        '1970-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12137',
        'Punjab Mail',
        'Mail',
        'Mail',
        'FZR',
        'CSTM',
        1930,
        60,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1912-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12345',
        'Saraighat Express',
        'Express',
        'Express',
        'HWH',
        'GHY',
        1000,
        55,
        100,
        20,
        TRUE,
        FALSE,
        'Active',
        '1984-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12627',
        'Karnataka Express',
        'Superfast',
        'Superfast',
        'SBC',
        'NDLS',
        2410,
        75,
        110,
        22,
        TRUE,
        TRUE,
        'Active',
        '1977-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12628',
        'Delhi Karnataka Exp',
        'Superfast',
        'Superfast',
        'NDLS',
        'SBC',
        2410,
        75,
        110,
        22,
        TRUE,
        TRUE,
        'Active',
        '1977-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12957',
        'Swarna Jayanti Rajdhani',
        'Rajdhani',
        'Superfast',
        'ADI',
        'NDLS',
        934,
        85,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1997-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12213',
        'Yesvantpur Duronto',
        'Duronto',
        'Superfast',
        'YPR',
        'NDLS',
        2365,
        90,
        130,
        20,
        TRUE,
        TRUE,
        'Active',
        '2010-01-01',
        FALSE,
        1.10,
        TRUE
    ),
    (
        '12030',
        'Amritsar Shatabdi',
        'Shatabdi',
        'Superfast',
        'ASR',
        'NDLS',
        448,
        85,
        120,
        18,
        TRUE,
        TRUE,
        'Active',
        '1988-01-01',
        FALSE,
        1.15,
        TRUE
    ),
    (
        '12029',
        'Delhi Amritsar Shatabdi',
        'Shatabdi',
        'Superfast',
        'NDLS',
        'ASR',
        448,
        85,
        120,
        18,
        TRUE,
        TRUE,
        'Active',
        '1988-01-01',
        FALSE,
        1.15,
        TRUE
    ),
    (
        '12437',
        'Secunderabad Rajdhani',
        'Rajdhani',
        'Superfast',
        'SC',
        'NZM',
        1670,
        85,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1997-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12438',
        'Delhi Secunderabad Raj',
        'Rajdhani',
        'Superfast',
        'NZM',
        'SC',
        1670,
        85,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1997-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12615',
        'Grand Trunk Express',
        'Superfast',
        'Superfast',
        'MAS',
        'NDLS',
        2182,
        70,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1929-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12616',
        'Delhi Grand Trunk Exp',
        'Superfast',
        'Superfast',
        'NDLS',
        'MAS',
        2182,
        70,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1929-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12723',
        'Telangana Express',
        'Superfast',
        'Superfast',
        'HYB',
        'NDLS',
        1670,
        75,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1976-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12724',
        'Delhi Telangana Exp',
        'Superfast',
        'Superfast',
        'NDLS',
        'HYB',
        1670,
        75,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1976-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12801',
        'Purushottam Express',
        'Superfast',
        'Superfast',
        'PURI',
        'NDLS',
        1860,
        70,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1978-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12802',
        'Delhi Purushottam Exp',
        'Superfast',
        'Superfast',
        'NDLS',
        'PURI',
        1860,
        70,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1978-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12955',
        'Mumbai Jaipur SF Exp',
        'Superfast',
        'Superfast',
        'BCT',
        'JP',
        1159,
        65,
        110,
        20,
        TRUE,
        FALSE,
        'Active',
        '1990-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12956',
        'Jaipur Mumbai SF Exp',
        'Superfast',
        'Superfast',
        'JP',
        'BCT',
        1159,
        65,
        110,
        20,
        TRUE,
        FALSE,
        'Active',
        '1990-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12303',
        'Poorva Express',
        'Superfast',
        'Superfast',
        'HWH',
        'NDLS',
        1447,
        75,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1970-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12304',
        'Delhi Poorva Express',
        'Superfast',
        'Superfast',
        'NDLS',
        'HWH',
        1447,
        75,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1970-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12917',
        'Gujarat Sampark Kranti',
        'Sampark Kranti',
        'Superfast',
        'ADI',
        'NZM',
        934,
        70,
        110,
        20,
        TRUE,
        FALSE,
        'Active',
        '2004-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12649',
        'Karnataka Sampark Kranti',
        'Sampark Kranti',
        'Superfast',
        'YPR',
        'NZM',
        2365,
        70,
        110,
        20,
        TRUE,
        FALSE,
        'Active',
        '2004-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12471',
        'Swaraj Express',
        'Superfast',
        'Superfast',
        'BDTS',
        'JAT',
        2025,
        70,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1990-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12472',
        'Jammu Swaraj Express',
        'Superfast',
        'Superfast',
        'JAT',
        'BDTS',
        2025,
        70,
        110,
        22,
        TRUE,
        FALSE,
        'Active',
        '1990-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '22436',
        'Vande Bharat Express',
        'Vande Bharat',
        'Superfast',
        'NDLS',
        'SVDK',
        655,
        85,
        180,
        16,
        TRUE,
        TRUE,
        'Active',
        '2019-01-01',
        FALSE,
        1.50,
        TRUE
    ),
    (
        '22435',
        'Delhi Vande Bharat',
        'Vande Bharat',
        'Superfast',
        'SVDK',
        'NDLS',
        655,
        85,
        180,
        16,
        TRUE,
        TRUE,
        'Active',
        '2019-01-01',
        FALSE,
        1.50,
        TRUE
    ),
    (
        '12309',
        'Rajendra Nagar Rajdhani',
        'Rajdhani',
        'Superfast',
        'RJPB',
        'NDLS',
        1000,
        85,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1996-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12953',
        'August Kranti Rajdhani',
        'Rajdhani',
        'Superfast',
        'NZM',
        'BCT',
        1386,
        90,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1992-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12954',
        'Mumbai August Kranti Raj',
        'Rajdhani',
        'Superfast',
        'BCT',
        'NZM',
        1386,
        90,
        130,
        22,
        TRUE,
        TRUE,
        'Active',
        '1992-01-01',
        FALSE,
        1.20,
        TRUE
    ),
    (
        '12297',
        'Pune Duronto',
        'Duronto',
        'Superfast',
        'PUNE',
        'NDLS',
        1515,
        85,
        130,
        20,
        TRUE,
        TRUE,
        'Active',
        '2011-01-01',
        FALSE,
        1.10,
        TRUE
    ),
    (
        '12298',
        'Delhi Pune Duronto',
        'Duronto',
        'Superfast',
        'NDLS',
        'PUNE',
        1515,
        85,
        130,
        20,
        TRUE,
        TRUE,
        'Active',
        '2011-01-01',
        FALSE,
        1.10,
        TRUE
    ),
    (
        '12307',
        'Howrah Jodhpur Exp',
        'Express',
        'Express',
        'HWH',
        'JU',
        1800,
        55,
        100,
        20,
        TRUE,
        FALSE,
        'Active',
        '1975-01-01',
        FALSE,
        1.00,
        TRUE
    ),
    (
        '12308',
        'Jodhpur Howrah Exp',
        'Express',
        'Express',
        'JU',
        'HWH',
        1800,
        55,
        100,
        20,
        TRUE,
        FALSE,
        'Active',
        '1975-01-01',
        FALSE,
        1.00,
        TRUE
    ) ON CONFLICT (train_number) DO NOTHING;

-- =============================================
-- ROUTES (For Major Trains - Sample Routes)
-- =============================================

-- Mumbai Rajdhani (12951): BCT -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12951',
        'BCT',
        1,
        NULL,
        '17:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        50
    ),
    (
        '12951',
        'BRC',
        2,
        '21:45',
        '21:50',
        5,
        392,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        80,
        30
    ),
    (
        '12951',
        'ST',
        3,
        '23:55',
        '23:58',
        3,
        521,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12951',
        'NDLS',
        4,
        '08:30',
        NULL,
        0,
        1386,
        2,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Howrah Rajdhani (12301): HWH -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12301',
        'HWH',
        1,
        NULL,
        '16:50',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        150,
        60
    ),
    (
        '12301',
        'GAYA',
        2,
        '22:15',
        '22:20',
        5,
        458,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12301',
        'PNBE',
        3,
        '23:45',
        '23:50',
        5,
        548,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        80,
        30
    ),
    (
        '12301',
        'CNB',
        4,
        '05:30',
        '05:35',
        5,
        1010,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12301',
        'NDLS',
        5,
        '11:30',
        NULL,
        0,
        1447,
        2,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Bhopal Shatabdi (12001): NDLS -> BPL
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12001',
        'NDLS',
        1,
        NULL,
        '06:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        120,
        40
    ),
    (
        '12001',
        'AGC',
        2,
        '08:30',
        '08:35',
        5,
        195,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        40,
        10
    ),
    (
        '12001',
        'GWL',
        3,
        '10:00',
        '10:05',
        5,
        315,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        40,
        10
    ),
    (
        '12001',
        'BPL',
        4,
        '13:30',
        NULL,
        0,
        707,
        1,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Chennai Rajdhani (12430): SBC -> NZM
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12430',
        'SBC',
        1,
        NULL,
        '20:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        40
    ),
    (
        '12430',
        'SC',
        2,
        '05:30',
        '05:40',
        10,
        700,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        80,
        30
    ),
    (
        '12430',
        'NGP',
        3,
        '13:00',
        '13:10',
        10,
        1280,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12430',
        'BPL',
        4,
        '18:00',
        '18:10',
        10,
        1650,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12430',
        'NZM',
        5,
        '05:00',
        NULL,
        0,
        2365,
        3,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Tamil Nadu Express (12621): MAS -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12621',
        'MAS',
        1,
        NULL,
        '22:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        150,
        50
    ),
    (
        '12621',
        'BZA',
        2,
        '06:00',
        '06:10',
        10,
        432,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        80,
        30
    ),
    (
        '12621',
        'NGP',
        3,
        '14:00',
        '14:10',
        10,
        1100,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        80,
        30
    ),
    (
        '12621',
        'BPL',
        4,
        '20:00',
        '20:10',
        10,
        1490,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12621',
        'AGC',
        5,
        '03:00',
        '03:05',
        5,
        1990,
        3,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        40,
        10
    ),
    (
        '12621',
        'NDLS',
        6,
        '07:00',
        NULL,
        0,
        2182,
        3,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Punjab Mail (12137): CSTM -> FZR
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12137',
        'CSTM',
        1,
        NULL,
        '19:35',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        120,
        40
    ),
    (
        '12137',
        'PUNE',
        2,
        '23:30',
        '23:40',
        10,
        192,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12137',
        'NGP',
        3,
        '12:00',
        '12:10',
        10,
        1080,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        80,
        30
    ),
    (
        '12137',
        'BPL',
        4,
        '18:00',
        '18:10',
        10,
        1470,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12137',
        'NDLS',
        5,
        '04:00',
        '04:20',
        20,
        2170,
        3,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12137',
        'FZR',
        6,
        '12:00',
        NULL,
        0,
        2440,
        3,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Vande Bharat (22436): NDLS -> SVDK
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '22436',
        'NDLS',
        1,
        NULL,
        '06:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        30
    ),
    (
        '22436',
        'UMB',
        2,
        '09:15',
        '09:20',
        5,
        200,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        40,
        10
    ),
    (
        '22436',
        'JAT',
        3,
        '13:30',
        '13:40',
        10,
        580,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        40,
        10
    ),
    (
        '22436',
        'SVDK',
        4,
        '15:30',
        NULL,
        0,
        655,
        1,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- August Kranti Rajdhani (12953): NZM -> BCT
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12953',
        'NZM',
        1,
        NULL,
        '17:15',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        50
    ),
    (
        '12953',
        'BRC',
        2,
        '21:40',
        '21:45',
        5,
        450,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12953',
        'BCT',
        3,
        '08:15',
        NULL,
        0,
        1386,
        2,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Pune Duronto (12297): PUNE -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12297',
        'PUNE',
        1,
        NULL,
        '16:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        40
    ),
    (
        '12297',
        'NGP',
        2,
        '01:00',
        '01:10',
        10,
        890,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12297',
        'BPL',
        3,
        '07:00',
        '07:10',
        10,
        1280,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12297',
        'NDLS',
        4,
        '15:00',
        NULL,
        0,
        1515,
        2,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Amritsar Shatabdi (12030): ASR -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12030',
        'ASR',
        1,
        NULL,
        '06:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        30
    ),
    (
        '12030',
        'JAT',
        2,
        '08:30',
        '08:35',
        5,
        210,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        40,
        10
    ),
    (
        '12030',
        'UMB',
        3,
        '11:00',
        '11:05',
        5,
        380,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        40,
        10
    ),
    (
        '12030',
        'NDLS',
        4,
        '13:30',
        NULL,
        0,
        448,
        1,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Telangana Express (12723): HYB -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12723',
        'HYB',
        1,
        NULL,
        '21:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        120,
        40
    ),
    (
        '12723',
        'SC',
        2,
        '21:30',
        '21:40',
        10,
        10,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12723',
        'NGP',
        3,
        '06:00',
        '06:10',
        10,
        800,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12723',
        'BPL',
        4,
        '12:00',
        '12:10',
        10,
        1180,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12723',
        'NDLS',
        5,
        '21:00',
        NULL,
        0,
        1670,
        2,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Purushottam Express (12801): PURI -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12801',
        'PURI',
        1,
        NULL,
        '19:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        40
    ),
    (
        '12801',
        'BBS',
        2,
        '20:30',
        '20:40',
        10,
        60,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        50,
        20
    ),
    (
        '12801',
        'NGP',
        3,
        '10:00',
        '10:10',
        10,
        850,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12801',
        'BPL',
        4,
        '16:00',
        '16:10',
        10,
        1220,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12801',
        'NDLS',
        5,
        '05:00',
        NULL,
        0,
        1860,
        3,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Karnataka Sampark Kranti (12649): YPR -> NZM
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12649',
        'YPR',
        1,
        NULL,
        '20:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        40
    ),
    (
        '12649',
        'GTL',
        2,
        '04:00',
        '04:10',
        10,
        500,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        50,
        20
    ),
    (
        '12649',
        'NGP',
        3,
        '13:00',
        '13:10',
        10,
        1100,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12649',
        'BPL',
        4,
        '19:00',
        '19:10',
        10,
        1500,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12649',
        'NZM',
        5,
        '06:00',
        NULL,
        0,
        2365,
        3,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Swaraj Express (12471): BDTS -> JAT
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12471',
        'BDTS',
        1,
        NULL,
        '14:30',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        40
    ),
    (
        '12471',
        'BRC',
        2,
        '21:00',
        '21:10',
        10,
        400,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12471',
        'NDLS',
        3,
        '10:00',
        '10:20',
        20,
        1200,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        80,
        30
    ),
    (
        '12471',
        'UMB',
        4,
        '14:00',
        '14:10',
        10,
        1400,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        50,
        20
    ),
    (
        '12471',
        'JAT',
        5,
        '20:00',
        NULL,
        0,
        2025,
        2,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Sealdah Duronto (12259): SDAH -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12259',
        'SDAH',
        1,
        NULL,
        '19:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        150,
        60
    ),
    (
        '12259',
        'DHN',
        2,
        '23:00',
        '23:10',
        10,
        280,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12259',
        'CNB',
        3,
        '07:00',
        '07:10',
        10,
        1100,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12259',
        'NDLS',
        4,
        '13:00',
        NULL,
        0,
        1453,
        2,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Mumbai Jaipur SF Express (12955): BCT -> JP
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12955',
        'BCT',
        1,
        NULL,
        '18:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        100,
        40
    ),
    (
        '12955',
        'ADI',
        2,
        '00:30',
        '00:40',
        10,
        490,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12955',
        'AII',
        3,
        '06:00',
        '06:10',
        10,
        850,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        50,
        20
    ),
    (
        '12955',
        'JP',
        4,
        '10:00',
        NULL,
        0,
        1159,
        2,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Grand Trunk Express (12615): MAS -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12615',
        'MAS',
        1,
        NULL,
        '20:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        150,
        50
    ),
    (
        '12615',
        'BZA',
        2,
        '04:00',
        '04:10',
        10,
        432,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        70,
        20
    ),
    (
        '12615',
        'NGP',
        3,
        '12:00',
        '12:10',
        10,
        1100,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        70,
        20
    ),
    (
        '12615',
        'BPL',
        4,
        '18:00',
        '18:10',
        10,
        1490,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12615',
        'AGC',
        5,
        '01:00',
        '01:05',
        5,
        1990,
        3,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        40,
        10
    ),
    (
        '12615',
        'NDLS',
        6,
        '06:00',
        NULL,
        0,
        2182,
        3,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- Poorva Express (12303): HWH -> NDLS
INSERT INTO
    train_master_schema.routes (
        train_number,
        station_code,
        sequence_number,
        arrival_time,
        departure_time,
        halt_duration,
        distance_from_origin,
        day_number,
        is_commercial_stop,
        is_originating_station,
        is_terminating_station,
        is_major_junction,
        booking_quota,
        waiting_list_quota
    )
VALUES (
        '12303',
        'HWH',
        1,
        NULL,
        '14:00',
        0,
        0,
        1,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        120,
        40
    ),
    (
        '12303',
        'DHN',
        2,
        '18:00',
        '18:10',
        10,
        280,
        1,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        50,
        20
    ),
    (
        '12303',
        'CNB',
        3,
        '03:00',
        '03:10',
        10,
        1100,
        2,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        60,
        20
    ),
    (
        '12303',
        'NDLS',
        4,
        '09:00',
        NULL,
        0,
        1447,
        2,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        0,
        0
    ) ON CONFLICT DO NOTHING;

-- =============================================
-- SEATS (Auto-generate for each train and class)
-- =============================================

-- Generate SL seats for all trains (12 coaches x 72 seats = 864 seats per train)
INSERT INTO
    train_master_schema.seats (
        train_number,
        coach_class,
        seat_number,
        berth_type,
        is_active
    )
SELECT
    t.train_number,
    'SL',
    'S' || c.coach_num || '-' || s.seat_num,
    CASE
        WHEN (s.seat_num - 1) % 8 IN (0, 1) THEN 'LOWER'
        WHEN (s.seat_num - 1) % 8 IN (2, 3) THEN 'MIDDLE'
        WHEN (s.seat_num - 1) % 8 IN (4, 5) THEN 'UPPER'
        WHEN (s.seat_num - 1) % 8 = 6 THEN 'SIDE_LOWER'
        ELSE 'SIDE_UPPER'
    END,
    TRUE
FROM
    train_master_schema.trains t
    CROSS JOIN generate_series (1, 12) AS c (coach_num)
    CROSS JOIN generate_series (1, 72) AS s (seat_num)
WHERE
    t.train_type IN (
        'Rajdhani',
        'Shatabdi',
        'Duronto',
        'Superfast',
        'Mail',
        'Express',
        'Sampark Kranti',
        'Garib Rath'
    ) ON CONFLICT (
        train_number,
        coach_class,
        seat_number
    ) DO NOTHING;

-- Generate 3A seats for premium trains (8 coaches x 72 seats = 576 seats per train)
INSERT INTO
    train_master_schema.seats (
        train_number,
        coach_class,
        seat_number,
        berth_type,
        is_active
    )
SELECT
    t.train_number,
    '3A',
    'B' || c.coach_num || '-' || s.seat_num,
    CASE
        WHEN (s.seat_num - 1) % 8 IN (0, 1) THEN 'LOWER'
        WHEN (s.seat_num - 1) % 8 IN (2, 3) THEN 'MIDDLE'
        WHEN (s.seat_num - 1) % 8 IN (4, 5) THEN 'UPPER'
        WHEN (s.seat_num - 1) % 8 = 6 THEN 'SIDE_LOWER'
        ELSE 'SIDE_UPPER'
    END,
    TRUE
FROM
    train_master_schema.trains t
    CROSS JOIN generate_series (1, 8) AS c (coach_num)
    CROSS JOIN generate_series (1, 72) AS s (seat_num)
WHERE
    t.train_type IN (
        'Rajdhani',
        'Duronto',
        'Superfast',
        'Mail',
        'Express',
        'Sampark Kranti',
        'Garib Rath'
    ) ON CONFLICT (
        train_number,
        coach_class,
        seat_number
    ) DO NOTHING;

-- Generate 2A seats for Rajdhani/Duronto trains (4 coaches x 54 seats = 216 seats per train)
INSERT INTO
    train_master_schema.seats (
        train_number,
        coach_class,
        seat_number,
        berth_type,
        is_active
    )
SELECT
    t.train_number,
    '2A',
    'A' || c.coach_num || '-' || s.seat_num,
    CASE
        WHEN (s.seat_num - 1) % 6 IN (0, 1) THEN 'LOWER'
        WHEN (s.seat_num - 1) % 6 IN (2, 3) THEN 'UPPER'
        WHEN (s.seat_num - 1) % 6 = 4 THEN 'SIDE_LOWER'
        ELSE 'SIDE_UPPER'
    END,
    TRUE
FROM
    train_master_schema.trains t
    CROSS JOIN generate_series (1, 4) AS c (coach_num)
    CROSS JOIN generate_series (1, 54) AS s (seat_num)
WHERE
    t.train_type IN ('Rajdhani', 'Duronto') ON CONFLICT (
        train_number,
        coach_class,
        seat_number
    ) DO NOTHING;

-- Generate 1A seats for Rajdhani trains (2 coaches x 24 seats = 48 seats per train)
INSERT INTO
    train_master_schema.seats (
        train_number,
        coach_class,
        seat_number,
        berth_type,
        is_active
    )
SELECT
    t.train_number,
    '1A',
    'H' || c.coach_num || '-' || s.seat_num,
    CASE
        WHEN (s.seat_num - 1) % 4 IN (0, 1) THEN 'LOWER'
        ELSE 'UPPER'
    END,
    TRUE
FROM
    train_master_schema.trains t
    CROSS JOIN generate_series (1, 2) AS c (coach_num)
    CROSS JOIN generate_series (1, 24) AS s (seat_num)
WHERE
    t.train_type IN ('Rajdhani') ON CONFLICT (
        train_number,
        coach_class,
        seat_number
    ) DO NOTHING;

-- Generate CC seats for Shatabdi trains (8 coaches x 78 seats = 624 seats per train)
INSERT INTO
    train_master_schema.seats (
        train_number,
        coach_class,
        seat_number,
        berth_type,
        is_active
    )
SELECT
    t.train_number,
    'CC',
    'C' || c.coach_num || '-' || s.seat_num,
    CASE
        WHEN (s.seat_num - 1) % 3 = 0 THEN 'WINDOW'
        WHEN (s.seat_num - 1) % 3 = 1 THEN 'AISLE'
        ELSE 'AISLE'
    END,
    TRUE
FROM
    train_master_schema.trains t
    CROSS JOIN generate_series (1, 8) AS c (coach_num)
    CROSS JOIN generate_series (1, 78) AS s (seat_num)
WHERE
    t.train_type IN ('Shatabdi', 'Vande Bharat') ON CONFLICT (
        train_number,
        coach_class,
        seat_number
    ) DO NOTHING;

-- Generate EC seats for Vande Bharat (2 coaches x 56 seats = 112 seats per train)
INSERT INTO
    train_master_schema.seats (
        train_number,
        coach_class,
        seat_number,
        berth_type,
        is_active
    )
SELECT
    t.train_number,
    'EC',
    'E' || c.coach_num || '-' || s.seat_num,
    CASE
        WHEN (s.seat_num - 1) % 2 = 0 THEN 'WINDOW'
        ELSE 'AISLE'
    END,
    TRUE
FROM
    train_master_schema.trains t
    CROSS JOIN generate_series (1, 2) AS c (coach_num)
    CROSS JOIN generate_series (1, 56) AS s (seat_num)
WHERE
    t.train_type IN ('Vande Bharat') ON CONFLICT (
        train_number,
        coach_class,
        seat_number
    ) DO NOTHING;

-- Generate 2S seats for all trains (4 coaches x 108 seats = 432 seats per train)
INSERT INTO
    train_master_schema.seats (
        train_number,
        coach_class,
        seat_number,
        berth_type,
        is_active
    )
SELECT
    t.train_number,
    '2S',
    'D' || c.coach_num || '-' || s.seat_num,
    CASE
        WHEN (s.seat_num - 1) % 2 = 0 THEN 'WINDOW'
        ELSE 'AISLE'
    END,
    TRUE
FROM
    train_master_schema.trains t
    CROSS JOIN generate_series (1, 4) AS c (coach_num)
    CROSS JOIN generate_series (1, 108) AS s (seat_num)
WHERE
    t.train_type IN (
        'Shatabdi',
        'Vande Bharat',
        'Superfast',
        'Mail',
        'Express'
    ) ON CONFLICT (
        train_number,
        coach_class,
        seat_number
    ) DO NOTHING;

-- =============================================
-- FARE MATRIX (Distance-based fares per train type and class)
-- =============================================

-- Sleeper (SL) Class Fares
INSERT INTO
    fare_schema.base_fare_matrix (
        train_type,
        coach_class,
        distance_from_km,
        distance_to_km,
        base_fare,
        minimum_fare,
        per_km_rate_beyond,
        is_active
    )
VALUES (
        'Express',
        'SL',
        1,
        10,
        20.00,
        30.00,
        2.00,
        TRUE
    ),
    (
        'Express',
        'SL',
        11,
        50,
        40.00,
        30.00,
        1.50,
        TRUE
    ),
    (
        'Express',
        'SL',
        51,
        100,
        60.00,
        30.00,
        1.20,
        TRUE
    ),
    (
        'Express',
        'SL',
        101,
        500,
        120.00,
        30.00,
        0.80,
        TRUE
    ),
    (
        'Express',
        'SL',
        501,
        1000,
        300.00,
        30.00,
        0.60,
        TRUE
    ),
    (
        'Express',
        'SL',
        1001,
        2000,
        500.00,
        30.00,
        0.50,
        TRUE
    ),
    (
        'Express',
        'SL',
        2001,
        5000,
        800.00,
        30.00,
        0.40,
        TRUE
    ),
    (
        'Superfast',
        'SL',
        1,
        10,
        25.00,
        35.00,
        2.50,
        TRUE
    ),
    (
        'Superfast',
        'SL',
        11,
        50,
        50.00,
        35.00,
        2.00,
        TRUE
    ),
    (
        'Superfast',
        'SL',
        51,
        100,
        75.00,
        35.00,
        1.50,
        TRUE
    ),
    (
        'Superfast',
        'SL',
        101,
        500,
        150.00,
        35.00,
        1.00,
        TRUE
    ),
    (
        'Superfast',
        'SL',
        501,
        1000,
        350.00,
        35.00,
        0.80,
        TRUE
    ),
    (
        'Superfast',
        'SL',
        1001,
        2000,
        600.00,
        35.00,
        0.60,
        TRUE
    ),
    (
        'Superfast',
        'SL',
        2001,
        5000,
        950.00,
        35.00,
        0.50,
        TRUE
    ),
    (
        'Mail',
        'SL',
        1,
        10,
        15.00,
        25.00,
        1.50,
        TRUE
    ),
    (
        'Mail',
        'SL',
        11,
        50,
        30.00,
        25.00,
        1.20,
        TRUE
    ),
    (
        'Mail',
        'SL',
        51,
        100,
        45.00,
        25.00,
        1.00,
        TRUE
    ),
    (
        'Mail',
        'SL',
        101,
        500,
        90.00,
        25.00,
        0.70,
        TRUE
    ),
    (
        'Mail',
        'SL',
        501,
        1000,
        250.00,
        25.00,
        0.50,
        TRUE
    ),
    (
        'Mail',
        'SL',
        1001,
        2000,
        450.00,
        25.00,
        0.45,
        TRUE
    ),
    (
        'Mail',
        'SL',
        2001,
        5000,
        700.00,
        25.00,
        0.35,
        TRUE
    ),
    (
        'Passenger',
        'SL',
        1,
        10,
        10.00,
        10.00,
        1.00,
        TRUE
    ),
    (
        'Passenger',
        'SL',
        11,
        50,
        20.00,
        10.00,
        0.80,
        TRUE
    ),
    (
        'Passenger',
        'SL',
        51,
        100,
        30.00,
        10.00,
        0.60,
        TRUE
    ),
    (
        'Passenger',
        'SL',
        101,
        500,
        60.00,
        10.00,
        0.40,
        TRUE
    ) ON CONFLICT DO NOTHING;

-- Third AC (3A) Class Fares
INSERT INTO
    fare_schema.base_fare_matrix (
        train_type,
        coach_class,
        distance_from_km,
        distance_to_km,
        base_fare,
        minimum_fare,
        per_km_rate_beyond,
        is_active
    )
VALUES (
        'Express',
        '3A',
        1,
        10,
        50.00,
        75.00,
        5.00,
        TRUE
    ),
    (
        'Express',
        '3A',
        11,
        50,
        100.00,
        75.00,
        4.00,
        TRUE
    ),
    (
        'Express',
        '3A',
        51,
        100,
        150.00,
        75.00,
        3.00,
        TRUE
    ),
    (
        'Express',
        '3A',
        101,
        500,
        300.00,
        75.00,
        2.00,
        TRUE
    ),
    (
        'Express',
        '3A',
        501,
        1000,
        750.00,
        75.00,
        1.50,
        TRUE
    ),
    (
        'Express',
        '3A',
        1001,
        2000,
        1200.00,
        75.00,
        1.20,
        TRUE
    ),
    (
        'Superfast',
        '3A',
        1,
        10,
        60.00,
        90.00,
        6.00,
        TRUE
    ),
    (
        'Superfast',
        '3A',
        11,
        50,
        120.00,
        90.00,
        5.00,
        TRUE
    ),
    (
        'Superfast',
        '3A',
        51,
        100,
        180.00,
        90.00,
        3.50,
        TRUE
    ),
    (
        'Superfast',
        '3A',
        101,
        500,
        350.00,
        90.00,
        2.50,
        TRUE
    ),
    (
        'Superfast',
        '3A',
        501,
        1000,
        850.00,
        90.00,
        1.80,
        TRUE
    ),
    (
        'Superfast',
        '3A',
        1001,
        2000,
        1400.00,
        90.00,
        1.50,
        TRUE
    ),
    (
        'Mail',
        '3A',
        1,
        10,
        40.00,
        60.00,
        4.00,
        TRUE
    ),
    (
        'Mail',
        '3A',
        11,
        50,
        80.00,
        60.00,
        3.00,
        TRUE
    ),
    (
        'Mail',
        '3A',
        51,
        100,
        120.00,
        60.00,
        2.50,
        TRUE
    ),
    (
        'Mail',
        '3A',
        101,
        500,
        250.00,
        60.00,
        1.80,
        TRUE
    ),
    (
        'Mail',
        '3A',
        501,
        1000,
        600.00,
        60.00,
        1.30,
        TRUE
    ),
    (
        'Mail',
        '3A',
        1001,
        2000,
        1000.00,
        60.00,
        1.00,
        TRUE
    ) ON CONFLICT DO NOTHING;

-- Second AC (2A) Class Fares
INSERT INTO
    fare_schema.base_fare_matrix (
        train_type,
        coach_class,
        distance_from_km,
        distance_to_km,
        base_fare,
        minimum_fare,
        per_km_rate_beyond,
        is_active
    )
VALUES (
        'Rajdhani',
        '2A',
        1,
        500,
        2000.00,
        500.00,
        4.00,
        TRUE
    ),
    (
        'Rajdhani',
        '2A',
        501,
        1000,
        2500.00,
        500.00,
        3.50,
        TRUE
    ),
    (
        'Rajdhani',
        '2A',
        1001,
        1500,
        3500.00,
        500.00,
        3.00,
        TRUE
    ),
    (
        'Rajdhani',
        '2A',
        1501,
        2000,
        4500.00,
        500.00,
        2.50,
        TRUE
    ),
    (
        'Rajdhani',
        '2A',
        2001,
        3000,
        5500.00,
        500.00,
        2.00,
        TRUE
    ),
    (
        'Duronto',
        '2A',
        1,
        500,
        1800.00,
        450.00,
        3.50,
        TRUE
    ),
    (
        'Duronto',
        '2A',
        501,
        1000,
        2200.00,
        450.00,
        3.00,
        TRUE
    ),
    (
        'Duronto',
        '2A',
        1001,
        1500,
        3200.00,
        450.00,
        2.50,
        TRUE
    ),
    (
        'Duronto',
        '2A',
        1501,
        2000,
        4000.00,
        450.00,
        2.00,
        TRUE
    ) ON CONFLICT DO NOTHING;

-- Third AC (3A) Rajdhani Fares
INSERT INTO
    fare_schema.base_fare_matrix (
        train_type,
        coach_class,
        distance_from_km,
        distance_to_km,
        base_fare,
        minimum_fare,
        per_km_rate_beyond,
        is_active
    )
VALUES (
        'Rajdhani',
        '3A',
        1,
        500,
        1500.00,
        400.00,
        3.00,
        TRUE
    ),
    (
        'Rajdhani',
        '3A',
        501,
        1000,
        2000.00,
        400.00,
        2.50,
        TRUE
    ),
    (
        'Rajdhani',
        '3A',
        1001,
        1500,
        2800.00,
        400.00,
        2.00,
        TRUE
    ),
    (
        'Rajdhani',
        '3A',
        1501,
        2000,
        3500.00,
        400.00,
        1.80,
        TRUE
    ),
    (
        'Rajdhani',
        '3A',
        2001,
        3000,
        4500.00,
        400.00,
        1.50,
        TRUE
    ),
    (
        'Duronto',
        '3A',
        1,
        500,
        1200.00,
        350.00,
        2.50,
        TRUE
    ),
    (
        'Duronto',
        '3A',
        501,
        1000,
        1600.00,
        350.00,
        2.00,
        TRUE
    ),
    (
        'Duronto',
        '3A',
        1001,
        1500,
        2400.00,
        350.00,
        1.80,
        TRUE
    ),
    (
        'Duronto',
        '3A',
        1501,
        2000,
        3200.00,
        350.00,
        1.50,
        TRUE
    ) ON CONFLICT DO NOTHING;

-- First AC (1A) Rajdhani Fares
INSERT INTO
    fare_schema.base_fare_matrix (
        train_type,
        coach_class,
        distance_from_km,
        distance_to_km,
        base_fare,
        minimum_fare,
        per_km_rate_beyond,
        is_active
    )
VALUES (
        'Rajdhani',
        '1A',
        1,
        500,
        3500.00,
        1000.00,
        7.00,
        TRUE
    ),
    (
        'Rajdhani',
        '1A',
        501,
        1000,
        4500.00,
        1000.00,
        6.00,
        TRUE
    ),
    (
        'Rajdhani',
        '1A',
        1001,
        1500,
        6000.00,
        1000.00,
        5.00,
        TRUE
    ),
    (
        'Rajdhani',
        '1A',
        1501,
        2000,
        7500.00,
        1000.00,
        4.00,
        TRUE
    ),
    (
        'Rajdhani',
        '1A',
        2001,
        3000,
        9000.00,
        1000.00,
        3.50,
        TRUE
    ) ON CONFLICT DO NOTHING;

-- AC Chair Car (CC) Shatabdi Fares
INSERT INTO
    fare_schema.base_fare_matrix (
        train_type,
        coach_class,
        distance_from_km,
        distance_to_km,
        base_fare,
        minimum_fare,
        per_km_rate_beyond,
        is_active
    )
VALUES (
        'Shatabdi',
        'CC',
        1,
        100,
        400.00,
        100.00,
        4.00,
        TRUE
    ),
    (
        'Shatabdi',
        'CC',
        101,
        300,
        600.00,
        100.00,
        3.00,
        TRUE
    ),
    (
        'Shatabdi',
        'CC',
        301,
        500,
        800.00,
        100.00,
        2.50,
        TRUE
    ),
    (
        'Shatabdi',
        'CC',
        501,
        1000,
        1200.00,
        100.00,
        2.00,
        TRUE
    ),
    (
        'Vande Bharat',
        'CC',
        1,
        100,
        500.00,
        150.00,
        5.00,
        TRUE
    ),
    (
        'Vande Bharat',
        'CC',
        101,
        300,
        800.00,
        150.00,
        4.00,
        TRUE
    ),
    (
        'Vande Bharat',
        'CC',
        301,
        500,
        1100.00,
        150.00,
        3.00,
        TRUE
    ),
    (
        'Vande Bharat',
        'CC',
        501,
        1000,
        1500.00,
        150.00,
        2.50,
        TRUE
    ) ON CONFLICT DO NOTHING;

-- Executive Chair Car (EC) Fares
INSERT INTO
    fare_schema.base_fare_matrix (
        train_type,
        coach_class,
        distance_from_km,
        distance_to_km,
        base_fare,
        minimum_fare,
        per_km_rate_beyond,
        is_active
    )
VALUES (
        'Shatabdi',
        'EC',
        1,
        100,
        800.00,
        200.00,
        8.00,
        TRUE
    ),
    (
        'Shatabdi',
        'EC',
        101,
        300,
        1200.00,
        200.00,
        6.00,
        TRUE
    ),
    (
        'Shatabdi',
        'EC',
        301,
        500,
        1600.00,
        200.00,
        5.00,
        TRUE
    ),
    (
        'Shatabdi',
        'EC',
        501,
        1000,
        2400.00,
        200.00,
        4.00,
        TRUE
    ),
    (
        'Vande Bharat',
        'EC',
        1,
        100,
        1000.00,
        250.00,
        10.00,
        TRUE
    ),
    (
        'Vande Bharat',
        'EC',
        101,
        300,
        1600.00,
        250.00,
        8.00,
        TRUE
    ),
    (
        'Vande Bharat',
        'EC',
        301,
        500,
        2200.00,
        250.00,
        6.00,
        TRUE
    ),
    (
        'Vande Bharat',
        'EC',
        501,
        1000,
        3000.00,
        250.00,
        5.00,
        TRUE
    ) ON CONFLICT DO NOTHING;

-- Second Sitting (2S) Fares
INSERT INTO
    fare_schema.base_fare_matrix (
        train_type,
        coach_class,
        distance_from_km,
        distance_to_km,
        base_fare,
        minimum_fare,
        per_km_rate_beyond,
        is_active
    )
VALUES (
        'Shatabdi',
        '2S',
        1,
        100,
        200.00,
        50.00,
        2.00,
        TRUE
    ),
    (
        'Shatabdi',
        '2S',
        101,
        300,
        300.00,
        50.00,
        1.50,
        TRUE
    ),
    (
        'Shatabdi',
        '2S',
        301,
        500,
        400.00,
        50.00,
        1.20,
        TRUE
    ),
    (
        'Shatabdi',
        '2S',
        501,
        1000,
        600.00,
        50.00,
        1.00,
        TRUE
    ) ON CONFLICT DO NOTHING;

-- =============================================
-- CANCELLATION CHARGES
-- =============================================

INSERT INTO
    fare_schema.cancellation_charges (
        hours_before_departure_min,
        hours_before_departure_max,
        cancellation_type,
        coach_class,
        charge_type,
        charge_value,
        minimum_charge,
        is_active
    )
VALUES (
        48,
        99999,
        'CONFIRMED',
        '1A',
        'PERCENTAGE',
        25.00,
        120.00,
        TRUE
    ),
    (
        48,
        99999,
        'CONFIRMED',
        '2A',
        'PERCENTAGE',
        25.00,
        120.00,
        TRUE
    ),
    (
        48,
        99999,
        'CONFIRMED',
        '3A',
        'PERCENTAGE',
        25.00,
        120.00,
        TRUE
    ),
    (
        48,
        99999,
        'CONFIRMED',
        'SL',
        'PERCENTAGE',
        25.00,
        60.00,
        TRUE
    ),
    (
        48,
        99999,
        'CONFIRMED',
        '2S',
        'PERCENTAGE',
        25.00,
        60.00,
        TRUE
    ),
    (
        24,
        48,
        'CONFIRMED',
        '1A',
        'PERCENTAGE',
        50.00,
        120.00,
        TRUE
    ),
    (
        24,
        48,
        'CONFIRMED',
        '2A',
        'PERCENTAGE',
        50.00,
        120.00,
        TRUE
    ),
    (
        24,
        48,
        'CONFIRMED',
        '3A',
        'PERCENTAGE',
        50.00,
        120.00,
        TRUE
    ),
    (
        24,
        48,
        'CONFIRMED',
        'SL',
        'PERCENTAGE',
        50.00,
        60.00,
        TRUE
    ),
    (
        12,
        24,
        'CONFIRMED',
        '1A',
        'PERCENTAGE',
        75.00,
        120.00,
        TRUE
    ),
    (
        12,
        24,
        'CONFIRMED',
        '2A',
        'PERCENTAGE',
        75.00,
        120.00,
        TRUE
    ),
    (
        12,
        24,
        'CONFIRMED',
        '3A',
        'PERCENTAGE',
        75.00,
        120.00,
        TRUE
    ),
    (
        12,
        24,
        'CONFIRMED',
        'SL',
        'PERCENTAGE',
        75.00,
        60.00,
        TRUE
    ),
    (
        4,
        12,
        'CONFIRMED',
        '1A',
        'PERCENTAGE',
        75.00,
        120.00,
        TRUE
    ),
    (
        4,
        12,
        'CONFIRMED',
        '2A',
        'PERCENTAGE',
        75.00,
        120.00,
        TRUE
    ),
    (
        4,
        12,
        'CONFIRMED',
        '3A',
        'PERCENTAGE',
        75.00,
        120.00,
        TRUE
    ),
    (
        4,
        12,
        'CONFIRMED',
        'SL',
        'PERCENTAGE',
        75.00,
        60.00,
        TRUE
    ),
    (
        0,
        4,
        'CONFIRMED',
        '1A',
        'PERCENTAGE',
        100.00,
        0,
        TRUE
    ),
    (
        0,
        4,
        'CONFIRMED',
        '2A',
        'PERCENTAGE',
        100.00,
        0,
        TRUE
    ),
    (
        0,
        4,
        'CONFIRMED',
        '3A',
        'PERCENTAGE',
        100.00,
        0,
        TRUE
    ),
    (
        0,
        4,
        'CONFIRMED',
        'SL',
        'PERCENTAGE',
        100.00,
        0,
        TRUE
    ),
    (
        0,
        99999,
        'RAC',
        'SL',
        'FLAT',
        60.00,
        60.00,
        TRUE
    ),
    (
        0,
        99999,
        'RAC',
        '3A',
        'FLAT',
        60.00,
        60.00,
        TRUE
    ),
    (
        0,
        99999,
        'WAITLIST',
        'SL',
        'FLAT',
        60.00,
        60.00,
        TRUE
    ),
    (
        0,
        99999,
        'WAITLIST',
        '3A',
        'FLAT',
        60.00,
        60.00,
        TRUE
    ) ON CONFLICT DO NOTHING;

-- =============================================
-- CONVENIENCE FEE CONFIG
-- =============================================

INSERT INTO
    fare_schema.convenience_fee_config (
        booking_channel,
        coach_class,
        fee_amount,
        gst_on_fee,
        is_active
    )
VALUES (
        'ONLINE',
        NULL,
        35.00,
        18.00,
        TRUE
    ),
    (
        'ONLINE',
        '1A',
        45.00,
        18.00,
        TRUE
    ),
    (
        'ONLINE',
        '2A',
        40.00,
        18.00,
        TRUE
    ),
    (
        'ONLINE',
        '3A',
        35.00,
        18.00,
        TRUE
    ),
    (
        'ONLINE',
        'SL',
        20.00,
        18.00,
        TRUE
    ),
    (
        'ONLINE',
        '2S',
        15.00,
        18.00,
        TRUE
    ),
    ('COUNTER', NULL, 0, 0, TRUE) ON CONFLICT DO NOTHING;